C#/MvcPWy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseOnline.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult HomePage()
        {
            return View("/Views/CMS/Home.cshtml");
        }
        public ActionResult Index()
        {
            //ViewBag.Link = TempData["ViewBagLink"];
            return View("/Views/Account/Login.cshtml");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [Authorize]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
        // GET: Home
    
}

C#/MvcPWy/Controllers/MenuDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseOnline.Controllers
{
    public class MenuDetailController : Controller
    {
        // GET: MenuDetail
        public ActionResult Index()
        {
            return View("/Views/CMS/MenuDetail.cshtml");
        }
    }
}

C#/MvcPWy/Views/CMS/Home.cshtml
@{
    Layout = "~/Views/Shared/_CMS_Layout.cshtml";
}

    <section class="content-header">
        <h1>
            Home Page
        </h1>
        <ol class="breadcrumb">
            <li><a href="dashboard.html"><i class="fa fa-dashboard"></i> Home</a></li>
        </ol>
    </section>

C#/MvcPWy/Views/CMS/MenuDetail.cshtml
@{
    Layout = "~/Views/Shared/_CMS_Layout.cshtml";
}

<section class="content-header">
    <h1>
        User Details
    </h1>
    <ol class="breadcrumb">
        <li><a href="dashboard.html"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="users-list.html">User List</a></li>
        <li class="active">User details</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#profile" data-toggle="tab">Profile</a></li>
                    <li><a href="#photo" data-toggle="tab">Photo</a></li>
                </ul>
                <div class="tab-content">
                    <div class="active tab-pane" id="profile">
                        <form class="form-horizontal">
                            <div class="form-group">
                                <label for="inputname" class="col-sm-2 control-label">Email</label>

                                <div class="col-sm-10">
                                    <input type="email" class="form-control" id="inputname"
                                           placeholder="Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="col-sm-2 control-label">Email</label>

                                <div class="col-sm-10">
                                    <input type="email" class="form-control" id="inputEmail"
                                           placeholder="Email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputMobile" class="col-sm-2 control-label">Mobile</label>

                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="inputMobile"
                                           placeholder="Mobile">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputForm" class="col-sm-2 control-label">Form</label>

                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="inputForm" placeholder="Form">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPosition" class="col-sm-2 control-label">Position</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="inputPosition"
                                           placeholder="Position">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3">How do we call you?</label>

                                <div class="col col-sm-2">
                                    <input type="radio" name="optionsRadios" id="optionsRadios1"
                                           value="option1" checked>
                                    Mr
                                </div>
                                <div class="col col-sm-2">
                                    <input type="radio" name="optionsRadios" id="optionsRadios2"
                                           value="option2">
                                    Ms
                                </div>
                                <div class="col col-sm-2">
                                    <input type="radio" name="optionsRadios" id="optionsRadios3"
                                           value="option3">
                                    Mrs
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"> Register to receive useful information
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">

                                <label class="col-sm-2 control-label">Roles</label>
                                <div class="col-sm-10">
                                    <select class="form-control">
                                        <option>Search and select roles</option>
                                        <option>option 2</option>
                                        <option>option 3</option>
                                        <option>option 4</option>
                                        <option>option 5</option>
                                    </select>
                                </div>

                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-danger">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="tab-pane tab-image" id="photo">
                        <img class="img-responsive pad" src="~/Assets/customimg/ronaldo.jpg" alt="Photo">
                        <div class="row tab-button">
                            <div class="form-group col-sm-5 col-sm-push-7">
                                <label for="exampleChange">Add/Change image</label>
                                <input class="custom-input" type="file" id="exampleChange">
                            </div>
                            <div class="form-group col-sm-7 col-sm-pull-5">
                                <div class="col-sm-offset-1">
                                    <button type="submit" class="btn btn-danger">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

C#/MvcPWy/Views/CMS/MenuList.cshtml
@{
    Layout = "~/Views/Shared/_CMS_Layout.cshtml";
}
<div class="box">
    <div class="box-body">
        <div class="table-responsive">
            <table id="tb_user" class="table table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Menu</th>
                        <th>Link</th>
                        <th>Order</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
            <br />
        </div>

    </div>
</div>
<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#tb_user').DataTable({
            "ajax": {
                "url": '@Url.Action("getAllMenu", "Menu")',
                "type": "POST",
                "datatype": "json",
            },
            "columns": [
                { "data": "menu_id", "name": "menu_id", "orderable": true },
                { "data": "menu_name", "name": "menu_name", "orderable": true },
                { "data": "menu_link", "name": "menu_link", "orderable": true },
                { "data": "menu_order", "name": "menu_order", "orderable": true },
                {
                    "data": "menu_status", "name": "menu_status", "orderable": true, "render": function (data) {
                        if (data == 1) return "active"
                        else return "unactive"}
                },
                {
                    "data": "menu_status", "render": function (data) {
                        if (data == 1) {
                            return "<a class='waves-effect waves-light btn-small blue darken-2 modal-trigger' data-target='edit_employee'  style='margin-left:5px' onclick=getIdMenu('" + data + "') ><i class='fa fa-fw fa-edit'></i>Edit</a>" +
                                "<a class='waves-effect waves-light btn-small red modal-trigger' style='margin-left:5px' onclick=getDeleteIdEmp('" + data + "') ><i class='fa fa-trash'></i>Inactive</a>";
                        } else
                            return "<a class='waves-effect waves-light btn-small blue darken-2 modal-trigger' data-target='edit_employee'  style='margin-left:5px' onclick=getIdMenu('" + data + "') ><i class='fa fa-fw fa-edit'></i>Edit</a>" +
                                "<a class='waves-effect waves-light btn-small red modal-trigger' style='margin-left:5px' onclick=getDeleteIdEmp('" + data + "') ><i class='fa fa-trash'></i>Active</a>";
                    },
                    "orderable": false,
                    "searchable": false
                },
            ],
        "paging": true,
        "pageLength": 5,
        "ordering": true,
        "serverSide": "true",
        "order": [[0, "asc"]],
        "searching": false
        });
    });
        function getIdMenu(id) {
            if (id != null) {
                window.location.href = '@Url.Action("getIdMenu","MenuDetail")?id=' + id;
            }
        }
    </script>
}

C#/MvcPWy/Views/CMS/PermissionsList.cshtml
@{
    Layout = "~/Views/Shared/_CMS_Layout.cshtml";
}
<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<section class="content-header">
    <h1>
        Permissions List
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Permissions List</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <a class="link" href="permission-details">Add New</a>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tb_permission" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th class="table-width5">ID</th>
                                <th class="table-width20">Permission</th>
                                <th class="table-width50">Link</th>
                                <th class="table-width5">Status</th>
                                <th class="table-width10">Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#tb_permission').DataTable({
             "ajax": {
                "url": '@Url.Action("GetAllPermissions", "Permissions")',
                "type": "POST",
                "datatype": "json",
            },
            "columns": [
                { "data": "permission_id", "name": "permission_id", "orderable": true },
                { "data": "permission_name", "name": "permission_name", "orderable": true },
                { "data": "permission_link", "name": "permission_link", "orderable": true },
                {
                    "data": "permission_status", "name": "permission_status", "orderable": true, "render": function (data) {
                        if (data == 1) return "active"
                        else return "unactive"}
                },
                {
                    "data": "permission_status", "render": function (data) {
                        if (data == 1) {
                            return "<a class='waves-effect waves-light btn-small blue darken-2 modal-trigger' data-target=''  style='margin-left:5px') ><i class='fa fa-fw fa-edit'></i>Edit</a>" +
                                "<a class='waves-effect waves-light btn-small red modal-trigger' style='margin-left:5px') ><i class='fa fa-trash'></i>Inactive</a>";
                        } else
                            return "<a class='waves-effect waves-light btn-small blue darken-2 modal-trigger' data-target=''  style='margin-left:5px') ><i class='fa fa-fw fa-edit'></i>Edit</a>" +
                                "<a class='waves-effect waves-light btn-small red modal-trigger' style='margin-left:5px') ><i class='fa fa-trash'></i>Active</a>";
                    },
                    "orderable": false,
                    "searchable": false
                },
            ],
        "paging": true,
        "pageLength": 5,
        "ordering": true,
        "serverSide": "true",
        "order": [[0, "asc"]],
        "searching": false
        });
    });
    </script>
}

C#/MvcPWy/Views/CMS/PostDetail.cshtml
@{
    ViewBag.Title = "PostDetail";
    Layout = "~/Views/Shared/_CMS_Layout.cshtml";
}
<section class="content-header">
    <h1>
        Post Details
    </h1>
    <ol class="breadcrumb">
        <li><a href="dashboard.html"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="posts-list.html">Post Lists</a></li>
        <li class="active">Post Details</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <div class="row">

        <div class="col-lg-12">
            <div class="nav-tabs-custom ">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#overview" data-toggle="tab">Overview</a></li>
                    <li><a href="#content" data-toggle="tab">Content</a></li>

                    <!-- /.tab-content -->
                </ul>
                <div class="tab-content">
                    <div class="active tab-pane" id="overview">
                        <div class="form-group">
                            <label>Text</label>
                            <input type="text" class="form-control" placeholder="Enter ..." id="txtName">
                        </div>
                        <div class="form-group">
                            <label>Short description</label>
                            <textarea class="form-control" rows="3" placeholder="Enter ..."></textarea>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col col-lg-3 col-md-3 col-sm-3 ">
                                    <label for="thumbnail">Thumbnail</label>
                                    <input class="custom-input" type="file" id="thumbnail">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Type</label>
                            <div class="row">
                                <div class="col col-lg-3 col-md-3 col-sm-3">
                                    <select class="form-control">
                                        <option>option 1</option>
                                        <option>option 2</option>
                                        <option>option 3</option>
                                        <option>option 4</option>
                                        <option>option 5</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Category</label>
                            <div class="row">
                                <div class="col col-lg-3 col-md-3 col-sm-3">
                                    <select class="form-control">
                                        <option>option 1</option>
                                        <option>option 2</option>
                                        <option>option 3</option>
                                        <option>option 4</option>
                                        <option>option 5</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- /.tab-pane -->
                    <div class="tab-pane" id="content">
                        <div class="box box-info">
                            <div class="box-header">
                                <h3 class="box-title">
                                    CK Editor
                                    <small>Advanced and full of features</small>
                                </h3>
                                <!-- tools box -->
                                <div class="pull-right box-tools">
                                    <button type="button" class="btn btn-info btn-sm" data-widget="collapse"
                                            data-toggle="tooltip" title="Collapse">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-info btn-sm" data-widget="remove"
                                            data-toggle="tooltip" title="Remove">
                                        <i class="fa fa-times"></i>
                                    </button>
                                </div>
                                <!-- /. tools -->
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body pad">
                                <form>
                                    <textarea id="editor1" name="editor1" rows="10" cols="80">
                                            This is my textarea to be replaced with CKEditor.
                    </textarea>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- /.tab-pane -->
                </div>
            </div>

            <!-- /.nav-tabs-custom -->
            <button class="btn btn-info" onclick = "getEdit()" >Edit</button>
            <button type="submit" class="btn btn-info">Submit</button>
            <button type="submit" class="btn btn-info">Public</button>
            <button type="submit" class="btn btn-info">Hide</button>
            <button type="submit" class="btn btn-info">Back</button>
        </div>


        <!-- /.col -->
    </div>
    <!-- /.row -->

</section>
@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>

    $(document).ready(function () {
        getBasicInfo();
    });

                         
        function getBasicInfo() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("getDetailPost","Post")',
            dataType: "json",
            success: function (data) {
               $('#txtName').val(data.data[0].post_name);
            },
        });
        }

        function getEdit() {
            alert("abc");
              $.ajax({
              type: "GET",
              url: @Url.Action("editPost", "Post"),
              success: function (data) {
               $("#myedit_syll").html(data)
              }

              });
        }
        function SubmitForm(form) {
                    $.validator.unobtrusive.parse(form);
                    if ($(form).valid()) {
                        $("#pre-load").show("slow", function () {
                        });
                        $("#pre-load").css("z-index", "99999");
                        $.ajax({
                            type: "POST",
                            url: form.action,
                            data: $(form).serialize(),
                            success: function (data) {
                                 alert("thanh cong");
                            },
                            error: function () {
                                alert("loi");
                            }
                        })
                    }
                    return false;
                }
    </script>
}

C#/MvcPWy/Views/CMS/PostList.cshtml
@{
    Layout = "~/Views/Shared/_CMS_Layout.cshtml";
}
<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />

<section class="content-header">
    <h1>
        Posts List
    </h1>
    <ol class="breadcrumb">
        <li><a href="dashboard.html"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Posts List</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <!-- /.box-header -->
                <a class="link" href="#">Add new</a>
                <div class="box-body">
                    <table id="tb_post" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th rowspan="2">ID</th>
                                <th rowspan="2">Thumbnail</th>
                                <th colspan="3" class="text-center">Post</th>
                                <th rowspan="2">Brief Info</th>
                                <th rowspan="2">Status</th>
                                <th rowspan="2">Action</th>
                            </tr>
                            <tr>
                                <th>Name</th>
                                <th>Category</th>
                                <th>Type</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#tb_post').DataTable({
            "ajax": {
                "url": '@Url.Action("GetAllPost", "Post")',
                "type": "POST",
                "datatype": "json",
            },
            "columns": [
                { "data": "post_id", "name": "post_id", "orderable": true },
                { "data": "post_thumbnail", "name": "post_thumbnail", "render": function(data) {
                    return "<img src='"+data+"'>";
                } },
                { "data": "post_name", "name": "post_name", "orderable": true },
                { "data": "post_category", "name": "post_category", "orderable": true },
                { "data": "post_type", "name": "post_type", "orderable": true },
                { "data": "post_brief_info", "name": "post_brief_info", "orderable": true },
                { "data": "post_status", "name": "post_status", "orderable": true },
                {
                    "data": "post_id", "render": function (data) {
                        return "<a class='waves-effect waves-light btn-small blue darken-2 modal-trigger' data-target='edit_employee'  style='margin-left:5px' onclick=getEditIdEmp('" + data + "') ><i class='fa fa-fw fa-edit'></i>Sửa</a>" ;
                    },
                    "orderable": false,
                    "searchable": false
                },

            ],
        "paging": true,
        "pageLength": 5,
        "ordering": true,
        "serverSide": "true",
        "order": [[0, "asc"]],
        "searching": false
        });
    });

        function getEditIdEmp(id) {
            if (id != null) {

            window.location.href ='@Url.Action("PostDetail", "Post")?id=' + id;

        }
    }
    </script>
}

C#/MvcPWy/Views/CMS/RolesPermission.cshtml
@{
    Layout = "~/Views/Shared/_CMS_Layout.cshtml";
}
<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<section class="content-header">
    <h1>
        Role Permissions
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Role Permission</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tb_permission_role" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th class="table-width5">ID</th>
                                <th class="table-width75">Menu</th>
                                <th class="table-width5">Role</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#tb_permission_role').DataTable({
             "ajax": {
                "url": '@Url.Action("GetRolePermission", "Permissions")',
                "type": "POST",
                "datatype": "json",
            },
            "columns": [
                { "data": "role_permission_id", "name": "role_permission_id", "orderable": true },
                { "data": "permissionName", "name": "permissionName", "orderable": true },
                { "data": "role_name", "name": "role_name", "orderable": true },
            ],
        "paging": true,
        "pageLength": 5,
        "ordering": true,
        "serverSide": "true",
        "order": [[0, "asc"]],
        "searching": false
        });
    });
    </script>
}